### ISSUE TITLE
Special characters cause hyperlinks to be displayed incorrectly

### ISSUE THREAD

**Issue by robincsmith** [moveworkforward/stash2slack#72]
PR titles like 'Upgrade MyLib 1.2.3 > 1.2.4' are causing hyperlinks in Stash to display incorrectly

<img width="427" alt="screen shot 2018-11-28 at 16 03 13" src="https://user-images.githubusercontent.com/23170929/49164510-2d0e8300-f327-11e8-8c8d-84c6cfb0f080.png">

The Slack hyperlink format is '<url|text>', so presumably, this problem is happening because the special '>' character in the PR title is not being escaped correctly?

This is on Bitbucket Server v5.8.0

**Comment by leonkyr** [comment]
Done.
